name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.docker.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.docker.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.docker.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve

    - name: Authenticate Docker to ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.docker.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.docker.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.docker.AWS_REGION }}

    - name: Build, tag, and push Docker image
      run: |
        docker build -t ${{ secrets.docker.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.docker.AWS_REGION }}.amazonaws.com/helloworld-php-apache:latest .
        docker push ${{ secrets.docker.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.docker.AWS_REGION }}.amazonaws.com/helloworld-php-apache:latest

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --region $(terraform -chdir=terraform output -raw region) --name $(terraform -chdir=terraform output -raw eks_cluster_name)

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
